# The script for auto-deploy releases

name: Deploy-Release

env:
  path1: "/root/AudioBridge1/nice2"

# The workflow will run when release is published
on:
  #push:
    #branches: [ develop ]
  release:
    types: [published]

# A workflow
jobs:
  AutoDeploy:
    runs-on: ubuntu-latest

    steps:
      #Connecting to server
      - name: Connecting to server
        uses: appleboy/ssh-action@master
        env:
          path2: "/root/AudioBridge1/nice1"
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            echo "${{env.path1}}"
            echo "${{env.path2}}"
            cd /root/AudioBridge1
            rm -rf AudioBridge
            git clone -b "${{ github.event.release.tag_name }}" --single-branch git@github.com:shonqwezon-team/AudioBridge.git
            cd AudioBridge
            chmod u+x install.zsh
            ./install.zsh
