# The script for auto-deploy debugging in from certain branch

name: Deploy-Debug

# The workflow will run when debugging is pushed into certain branch
on: push

env:
  branch_name: "-add_sql_support"

# A workflow
jobs:
  CheckBranch:
    runs-on: ubuntu-latest
    if: ${{ github.ref_name == env.branch_name }}
    steps:
      - name: Init
        run:
          echo "${{ github.ref_name }} $branch_name"

  Deploying:
      runs-on: ubuntu-latest
      needs: CheckBranch
    
      steps:
        #Connecting to server
        - name: Connecting to server
          run: 
            echo "OK"
