# The script for auto-deploy dev version in from dev branch

name: Deploy-Dev

# The workflow will run when debugging is pushed into dev branch
on:
  push:
    branches:
      - dev
      - 'release/*'

# A workflow
jobs:
  DevDeploy:
    runs-on: ubuntu-latest
    steps:
      #Connecting to server
      - name: Connecting to server
        uses: appleboy/ssh-action@master
        with:
          host    : ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key     : ${{ secrets.SSH_KEY }}
          port    : ${{ secrets.SSH_PORT }}
          script: |
            cd /root/AudioBridge
            rm -rf dev
            git clone -b dev --single-branch git@github.com:AudioBridge-team/AudioBridge.git dev
            cd dev
            chmod u+x install.zsh
            ./install.zsh -d
