# The script for auto-deploy debugging in from certain branch

name: Deploy-Debug

# The workflow will run when debugging is pushed into certain branch
on:
  push:
    branches-ignore:
      - main

env:
  branch_name: "add_sql_support"

# A workflow
jobs:
  DebugDeploy:
    runs-on: ubuntu-latest

    steps:
      #Branch verification
      - name: Branch verification
        run:
          echo "(${{ github.ref_name }} is ${{ env.branch_name }}) = ${{ github.ref_name == env.branch_name }}"
      #Connecting to server
      - name: Connecting to server
        env:
          dir: "AudioBridge-${{ env.branch_name }}"
        if: ${{ github.ref_name == env.branch_name }}
        uses: appleboy/ssh-action@master
        with:
          host    : ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key     : ${{ secrets.SSH_KEY }}
          port    : ${{ secrets.SSH_PORT }}
          script: |
            cd /root
            rm -rf "$dir"
            git clone -b "${{ env.branch_name }}" --single-branch git@github.com:shonqwezon-team/AudioBridge.git "$dir"
            cd "$dir"
            chmod u+x install.zsh
            ./install.zsh -v "${{ env.branch_name }}" -d
