# The script for auto-deploy releases

name: Deploy-Release

# The workflow will run when release is published
on:
  push:
    branches: [ develop ]
  #release:
    #types: [published]

# A workflow
jobs:
  Deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:

      #Connecting to server
      - id: ssh
        uses: invi5H/ssh-action@v1
        with:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_PORT: ${{ secrets.SSH_PORT }}
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
      - run: ssh ${{ steps.ssh.outputs.SERVER }} pwd

      #Check
      - name: Test command
        run: ls
