# The script for auto-deploy releases

name: Deploy-Release

# The workflow will run when release is published
on:
  release:
    types: [ published ]

# A workflow
jobs:
  ReleaseDeploy:
    runs-on: ubuntu-latest

    steps:
      #Connecting to server
      - name: Connecting to server
        uses: appleboy/ssh-action@master
        with:
          host    : ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key     : ${{ secrets.SSH_KEY }}
          port    : ${{ secrets.SSH_PORT }}
          script: |
            cd /root
            rm -rf AudioBridge
            git clone -b "${{ github.event.release.tag_name }}" --single-branch git@github.com:shonqwezon-team/AudioBridge.git
            cd AudioBridge
            chmod u+x install.zsh
            ./install.zsh -v "${{ github.event.release.tag_name }}"
