# The script for auto-deploy debugging in from certain branch

name: Deploy-Debug

# The workflow will run when debugging is pushed into certain branch
on: push

env:
  branch_name: "add_sql_support"
  bool_test: true

# A workflow
jobs:
  CheckBranch:
    runs-on: ubuntu-latest
    steps:
      - name: Init
        run:
          echo "${{ github.ref_name == env.branch_name }}"

  Deploying:
      runs-on: ubuntu-latest
      if: env.bool_test=='true'
      needs: CheckBranch
    
      steps:
        #Connecting to server
        - name: Connecting to server
          run: 
            echo "OK"
